import {
  Student,
  Mentor,
  Department,
  Shift,
  GpsVerification,
  DepartmentAlert,
  AdminActivityLog,
  HospitalGeofence,
  UserProfile,
} from '../types';

export const HOSPITAL_CONFIG: HospitalGeofence = {
  name: 'InternPulse General Hospital',
  latitude: 13.0827,
  longitude: 80.2707,
  radius_meters: 150,
};

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift_night',
    name: 'Night Shift',
    start_time: '22:00',
    end_time: '06:00',
    label: 'Night (10:00 PM - 06:00 AM)',
    is_continuous_night: true,
  },
  {
    id: 'shift_morning',
    name: 'Morning Shift',
    start_time: '06:00',
    end_time: '14:00',
    label: 'Morning (06:00 AM - 02:00 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_evening',
    name: 'Evening Shift',
    start_time: '14:00',
    end_time: '22:00',
    label: 'Evening (02:00 PM - 10:00 PM)',
    is_continuous_night: false,
  },
];

export const INITIAL_MENTORS: Mentor[] = [
  {
    id: 'mentor01',
    name: 'Dr. Anitha',
    title: 'Senior Clinical Supervisor',
    department: 'Radiology',
    hospital: 'InternPulse General Hospital',
    assigned_students_count: 3,
  },
  {
    id: 'mentor02',
    name: 'Dr. Sarah Mitchell',
    title: 'Clinical Supervisor & HOD',
    department: 'Cardiology',
    hospital: 'InternPulse General Hospital',
    assigned_students_count: 2,
  },
  {
    id: 'mentor03',
    name: 'Dr. L. Chen',
    title: 'Emergency Medicine Supervisor',
    department: 'Emergency Medicine',
    hospital: 'InternPulse General Hospital',
    assigned_students_count: 2,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept_radiology',
    name: 'Radiology & Imaging',
    code: 'RAD',
    hod_name: 'Dr. Sarah Mitchell',
    total_students: 24,
    active_interns: 18,
    on_shift: 8,
    verified_today: 19,
    needs_attention: 1,
    gps_unavailable: 1,
  },
  {
    id: 'dept_cardiology',
    name: 'Cardiovascular Tech',
    code: 'CVT',
    hod_name: 'Dr. Ramesh Rao',
    total_students: 20,
    active_interns: 14,
    on_shift: 6,
    verified_today: 18,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_emergency',
    name: 'Emergency & Critical Care',
    code: 'ECC',
    hod_name: 'Dr. K. Srinivas',
    total_students: 20,
    active_interns: 16,
    on_shift: 7,
    verified_today: 15,
    needs_attention: 1,
    gps_unavailable: 0,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    register_number: 'AHS001',
    name: 'Arun Kumar',
    department: 'Radiology',
    mentor_id: 'mentor01',
    mentor_name: 'Dr. Anitha',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_night',
    shift_name: 'Night Shift',
    shift_time: '10:00 PM – 06:00 AM',
    is_night_shift: true,
    is_active_shift: true,
    shift_started_at: '2026-08-27T22:00:00Z',
    current_status: 'NEEDS ATTENTION',
    last_verified_at: '03:42 AM',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    register_number: 'AHS002',
    name: 'Priya Sharma',
    department: 'Radiology',
    mentor_id: 'mentor01',
    mentor_name: 'Dr. Anitha',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_morning',
    shift_name: 'Morning Shift',
    shift_time: '06:00 AM – 02:00 PM',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'VERIFIED',
    last_verified_at: '01:45 PM',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    register_number: 'AHS003',
    name: 'Karthik Raman',
    department: 'Radiology',
    mentor_id: 'mentor01',
    mentor_name: 'Dr. Anitha',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_night',
    shift_name: 'Night Shift',
    shift_time: '10:00 PM – 06:00 AM',
    is_night_shift: true,
    is_active_shift: true,
    shift_started_at: '2026-08-27T22:05:00Z',
    current_status: 'GPS UNAVAILABLE',
    last_verified_at: '02:15 AM',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    register_number: 'AHS004',
    name: 'Rajesh Patel',
    department: 'Cardiology',
    mentor_id: 'mentor02',
    mentor_name: 'Dr. Sarah Mitchell',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_night',
    shift_name: 'Night Shift',
    shift_time: '10:00 PM – 06:00 AM',
    is_night_shift: true,
    is_active_shift: true,
    shift_started_at: '2026-08-27T22:00:00Z',
    current_status: 'VERIFIED',
    last_verified_at: '03:30 AM',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    register_number: 'AHS005',
    name: 'Meera Nair',
    department: 'Emergency Medicine',
    mentor_id: 'mentor03',
    mentor_name: 'Dr. L. Chen',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_night',
    shift_name: 'Night Shift',
    shift_time: '10:00 PM – 06:00 AM',
    is_night_shift: true,
    is_active_shift: true,
    shift_started_at: '2026-08-27T22:00:00Z',
    current_status: 'NEEDS ATTENTION',
    last_verified_at: '03:15 AM',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    register_number: 'AHS006',
    name: 'Divya Suresh',
    department: 'Emergency Medicine',
    mentor_id: 'mentor03',
    mentor_name: 'Dr. L. Chen',
    hospital: 'InternPulse General Hospital',
    shift_id: 'shift_night',
    shift_name: 'Night Shift',
    shift_time: '10:00 PM – 06:00 AM',
    is_night_shift: true,
    is_active_shift: true,
    shift_started_at: '2026-08-27T22:00:00Z',
    current_status: 'VERIFIED',
    last_verified_at: '04:00 AM',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VERIFICATIONS: GpsVerification[] = [
  {
    id: 'v_arun_1',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-27T22:15:00Z',
    time_display: '10:15 PM',
    status: 'VERIFIED',
    distance_meters: 28,
    accuracy_meters: 5,
    latitude: 13.0828,
    longitude: 80.2708,
    is_inside_geofence: true,
    verification_type: 'SHIFT_START',
  },
  {
    id: 'v_arun_2',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-28T00:05:00Z',
    time_display: '12:05 AM',
    status: 'VERIFIED',
    distance_meters: 42,
    accuracy_meters: 4,
    latitude: 13.0825,
    longitude: 80.2709,
    is_inside_geofence: true,
    verification_type: 'SCHEDULED',
  },
  {
    id: 'v_arun_3',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-28T02:10:00Z',
    time_display: '02:10 AM',
    status: 'VERIFIED',
    distance_meters: 35,
    accuracy_meters: 6,
    latitude: 13.0826,
    longitude: 80.2706,
    is_inside_geofence: true,
    verification_type: 'RANDOM_PROMPT',
  },
  {
    id: 'v_arun_4',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-28T03:42:00Z',
    time_display: '03:42 AM',
    status: 'NEEDS ATTENTION',
    distance_meters: 420,
    accuracy_meters: 8,
    latitude: 13.0855,
    longitude: 80.2742,
    is_inside_geofence: false,
    verification_type: 'RANDOM_PROMPT',
  },
  {
    id: 'v_arun_5',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-28T04:15:00Z',
    time_display: '04:15 AM',
    status: 'VERIFIED',
    distance_meters: 48,
    accuracy_meters: 5,
    latitude: 13.0829,
    longitude: 80.2705,
    is_inside_geofence: true,
    verification_type: 'SCHEDULED',
  },
  {
    id: 'v_arun_6',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    timestamp: '2026-08-28T05:30:00Z',
    time_display: '05:30 AM',
    status: 'VERIFIED',
    distance_meters: 30,
    accuracy_meters: 4,
    latitude: 13.0827,
    longitude: 80.2707,
    is_inside_geofence: true,
    verification_type: 'SCHEDULED',
  },
];

export const INITIAL_ALERTS: DepartmentAlert[] = [
  {
    id: 'alert_arun_01',
    verification_id: 'v_arun_4',
    register_number: 'AHS001',
    student_name: 'Arun Kumar',
    department: 'Radiology',
    mentor_id: 'mentor01',
    mentor_name: 'Dr. Anitha',
    triggered_at: '2026-08-28T03:42:00Z',
    time_display: '03:42 AM',
    status: 'NEEDS ATTENTION',
    distance_meters: 420,
    accuracy_meters: 8,
    reason: 'Geofence Breach: 420m from hospital perimeter during active night shift',
  },
  {
    id: 'alert_meera_01',
    verification_id: 'v_meera_1',
    register_number: 'AHS005',
    student_name: 'Meera Nair',
    department: 'Emergency Medicine',
    mentor_id: 'mentor03',
    mentor_name: 'Dr. L. Chen',
    triggered_at: '2026-08-28T03:15:00Z',
    time_display: '03:15 AM',
    status: 'NEEDS ATTENTION',
    distance_meters: 380,
    accuracy_meters: 10,
    reason: 'Geofence Breach: 380m from perimeter during critical triage rotation',
  },
];

export const INITIAL_LOGS: AdminActivityLog[] = [
  {
    id: 'log_001',
    timestamp: '2026-08-27 21:30',
    action_type: 'SHIFT_CHANGE',
    student_register_number: 'AHS001',
    student_name: 'Arun Kumar',
    details: 'Shift assigned to Night (10:00 PM - 06:00 AM)',
    reason: 'Rotational schedule allocation for Radiology Department block',
    performed_by: 'admin01 (Operations)',
  },
  {
    id: 'log_002',
    timestamp: '2026-08-27 18:00',
    action_type: 'MENTOR_REASSIGN',
    student_register_number: 'AHS003',
    student_name: 'Karthik Raman',
    details: 'Mentor assigned to Dr. Anitha',
    reason: 'Supervision load balance across Radiology team',
    performed_by: 'admin01 (Operations)',
  },
];

export const DEMO_USERS: Record<string, UserProfile> = {
  AHS001: {
    id: 'student_arun',
    registerNumber: 'AHS001',
    name: 'Arun Kumar',
    role: 'STUDENT',
    department: 'Radiology',
    email: 'arun.kumar@student.ahs.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  mentor01: {
    id: 'mentor01',
    name: 'Dr. Anitha',
    role: 'MENTOR',
    department: 'Radiology',
    email: 'dr.anitha@hospital.org',
    avatar: 'https://images.unsplash.com/photo-1594824813589-3221e7d23d8c?w=150&auto=format&fit=crop&q=80',
  },
  hod01: {
    id: 'hod01',
    name: 'Dr. Sarah Mitchell',
    role: 'HOD',
    department: 'Radiology',
    email: 'hod.radiology@hospital.org',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  },
  admin01: {
    id: 'admin01',
    name: 'Clinical Admin Office',
    role: 'ADMIN',
    department: 'Hospital Administration',
    email: 'admin.internship@hospital.org',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  },
};
